index:
   path: /
   controller: App\Controller\DefaultController::index
category:
   path: /category-{id}
   controller: App\Controller\DefaultController::category
product:
   path: /{Parent}/product-{id}
   controller: App\Controller\DefaultController::product  